import type { DashboardPayload } from "@/lib/types";

export const mockPayload: DashboardPayload = {
  source: "mock",
  generatedAt: new Date("2026-05-14T12:00:00.000Z").toISOString(),
  fallbackReason: "GitHub API unavailable, loading curated mock signal set.",
  profile: {
    login: "signalcraft",
    name: "Signal Craft Studio",
    avatarUrl: "https://avatars.githubusercontent.com/u/583231?v=4",
    bio: "Designing products, interfaces and data systems with a sharper operational lens.",
    followers: 842,
    following: 19,
    publicRepos: 9,
    htmlUrl: "https://github.com/octocat",
  },
  repos: [
    {
      id: 1,
      name: "radar-core",
      fullName: "signalcraft/radar-core",
      description: "Telemetry kernel for internal product observability.",
      language: "TypeScript",
      stars: 860,
      forks: 124,
      openIssues: 12,
      watchers: 860,
      size: 2100,
      archived: false,
      updatedAt: "2026-05-13T18:21:00.000Z",
      htmlUrl: "https://github.com/octocat/Hello-World",
    },
    {
      id: 2,
      name: "glass-ui",
      fullName: "signalcraft/glass-ui",
      description: "High-fidelity component system for desktop-grade interfaces.",
      language: "React",
      stars: 640,
      forks: 88,
      openIssues: 7,
      watchers: 640,
      size: 1320,
      archived: false,
      updatedAt: "2026-05-10T14:12:00.000Z",
      htmlUrl: "https://github.com/octocat/Hello-World",
    },
    {
      id: 3,
      name: "event-map",
      fullName: "signalcraft/event-map",
      description: "Geo signal analytics and event reconciliation tools.",
      language: "Python",
      stars: 420,
      forks: 63,
      openIssues: 18,
      watchers: 420,
      size: 1780,
      archived: false,
      updatedAt: "2026-04-29T10:04:00.000Z",
      htmlUrl: "https://github.com/octocat/Hello-World",
    },
    {
      id: 4,
      name: "fusion-notes",
      fullName: "signalcraft/fusion-notes",
      description: "Research workspace for product notes and synthesis.",
      language: "Go",
      stars: 275,
      forks: 31,
      openIssues: 5,
      watchers: 275,
      size: 860,
      archived: false,
      updatedAt: "2026-04-18T22:40:00.000Z",
      htmlUrl: "https://github.com/octocat/Hello-World",
    },
    {
      id: 5,
      name: "interface-lab",
      fullName: "signalcraft/interface-lab",
      description: "Experimental visual systems and chart interaction prototypes.",
      language: "TypeScript",
      stars: 510,
      forks: 54,
      openIssues: 9,
      watchers: 510,
      size: 950,
      archived: false,
      updatedAt: "2026-03-30T11:20:00.000Z",
      htmlUrl: "https://github.com/octocat/Hello-World",
    },
    {
      id: 6,
      name: "quiet-queue",
      fullName: "signalcraft/quiet-queue",
      description: "Task orchestration service for calm operational workflows.",
      language: "Rust",
      stars: 390,
      forks: 47,
      openIssues: 6,
      watchers: 390,
      size: 1120,
      archived: false,
      updatedAt: "2026-03-14T09:15:00.000Z",
      htmlUrl: "https://github.com/octocat/Hello-World",
    },
    {
      id: 7,
      name: "watch-tower",
      fullName: "signalcraft/watch-tower",
      description: "Realtime issue monitoring for service health and API variance.",
      language: "TypeScript",
      stars: 330,
      forks: 29,
      openIssues: 14,
      watchers: 330,
      size: 1180,
      archived: false,
      updatedAt: "2026-02-21T16:55:00.000Z",
      htmlUrl: "https://github.com/octocat/Hello-World",
    },
    {
      id: 8,
      name: "beam-ml",
      fullName: "signalcraft/beam-ml",
      description: "Forecasting experiments for product and usage signal intensity.",
      language: "Python",
      stars: 290,
      forks: 40,
      openIssues: 10,
      watchers: 290,
      size: 1640,
      archived: false,
      updatedAt: "2026-01-27T07:44:00.000Z",
      htmlUrl: "https://github.com/octocat/Hello-World",
    },
  ],
};
